### ISSUE TITLE
Proposed API changes

### ISSUE THREAD

**Issue by autarch** [benkasminbullock/xs-check#2]
I'd really like to wrap this with a test module, but the current API makes that challenging.

Just warning out errors makes it hard to capture them for test diagnostics. What I'd really like is to get the errors back from the `check` and `check_file` methods.

Would you be up for a PR to change this?

**Comment by benkasminbullock** [comment]
All of the errors made by the module go through a routine called "report",
so changing it from using "warn" to a user-defined way of reporting is just
a matter of tweaking "report". What I've done provisionally is to add a
"reporter" field to the "new" method, and you can do whatever you like with
the outputs. For convenience it uses a hash as arguments with the methods
described.

This is on CPAN as the following update:

https://metacpan.org/pod/release/BKB/XS-Check-0.07/lib/XS/Check.pm

Due to a previous error the links to example code in the documentation
don't work correctly. That has already been fixed:

3da87918e043147952ed3fcf0dc2809a8797ad91

The example is here:

https://fastapi.metacpan.org/source/BKB/XS-Check-0.07/examples/reporter.pl

**Comment by autarch** [comment]
Works for me. Thanks!
